spring:
  application:
    name: BWWeb
  datasource:
    url: jdbc:mysql://localhost:3306/testspr
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/hjl/mapper/*.xml
server:
  port: 10021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka, http://localhost:10011/eureka
